os: linux
dist: bionic
addons:
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - dpkg
      - google-chrome-stable
language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
  
script:
  - wget https://chromedriver.storage.googleapis.com/85.0.4183.87/chromedriver_mac64.zip 
  - unzip *.zip 
  - sudo mv chromedriver /usr/local/bin 
  - echo "export PATH=$HOME/usr/bin:/usr/local.bin:$PATH" >> .bashrc 
  - robot tests/tests.robot