os: linux
dist: bionic
sudo: required 
addons:
  apt: 
    update: true
    sources:
      - google-chrome
    packages:
      - dpkg
      - google-chrome-stable
language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
  
script:
  - robot tests/tests.robot